version: 1

models:
  eeg:
    target: base.vae.VAE
    params:
    
  subject_cls:
    target: base.models.MLP
    params:
        input_dim: 512
        output_dim: 10


data:
  data_dir: /dev/shm/wht/datasets/things-eeg-small/Preprocessed_data_250Hz_whiten
  subjects: ['sub-08'] #'sub-01','sub-02' ,'sub-03', 'sub-04', 'sub-05', 'sub-06', 'sub-07', 'sub-08', 'sub-09', 'sub-10']
  selected_ch: ['P7', 'P5', 'P3', 'P1','Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3', 'POz', 'PO4', 'PO8','O1', 'Oz', 'O2']
  clip_feature: ViT-B-32
  train_val_rate: 0.8
  train_batch_size: 4096
  test_batch_size: 200
  train_avg: False
  test_avg: False

train:
  epoch: 100
  optimizer: AdamW
  lr: 1e-4

save_dir: '/home/wht/multimodal_brain/src/tasks/exp'